create table td_task (id int8 generated by default as identity, description varchar(255), status int4, title varchar(255), primary key (id));
create table td_task (id int8 generated by default as identity, description varchar(255), status int4, title varchar(255), primary key (id));
create table tb_task (id int8 generated by default as identity, description varchar(255), status int4, title varchar(255), primary key (id));
create table tb_task (id int8 generated by default as identity, description varchar(255), status int4, title varchar(255), primary key (id));
